# Generated by Django 3.2 on 2021-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_candle_quote_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(),
        ),
    ]
