# Generated by Django 3.2 on 2021-06-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSV', models.FileField(upload_to='')),
            ],
        ),
    ]
