# Generated by Django 3.2 on 2021-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_auto_20210614_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='marketcap',
            field=models.CharField(max_length=8),
        ),
    ]
