# Generated by Django 3.2 on 2021-06-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_auto_20210614_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currentR',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quickR',
            field=models.CharField(max_length=8),
        ),
    ]
