# Generated by Django 3.2 on 2021-06-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_auto_20210614_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='averagevolume',
            field=models.CharField(max_length=8),
        ),
    ]
