# Generated by Django 3.2 on 2021-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_alter_stock_averagevolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('change', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='RSI',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='debtequity',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fwdpe',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='longdebtequity',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='partcert',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='peg',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pfcf',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pricetobook',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pricetoearnings',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pricetosales',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='recom',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='relativeVolume',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shortratio',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.CharField(max_length=18),
        ),
    ]
