# Generated by Django 3.2 on 2021-06-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0013_auto_20210614_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adjclose', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=9)),
                ('moments', models.ManyToManyField(blank=True, to='welcome.moment')),
            ],
        ),
    ]
