# Generated by Django 3.2 on 2021-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0014_moment_stockhandle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='welcome.Stock'),
        ),
    ]
