# Generated by Django 3.2 on 2021-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0015_auto_20210616_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('company', models.CharField(max_length=64)),
                ('exchange', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('range', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=8)),
                ('currency', models.CharField(max_length=8)),
                ('shares', models.CharField(max_length=8)),
                ('actions', models.CharField(max_length=16)),
            ],
        ),
    ]
