# Generated by Django 3.2 on 2021-06-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_ipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=9)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('change', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='ipo',
            name='date',
            field=models.CharField(max_length=64),
        ),
    ]
