# Generated by Django 3.2 on 2021-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0017_auto_20210623_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptostock',
            name='adjclose',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
