# Generated by Django 3.2 on 2021-06-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0018_cryptostock_adjclose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptostock',
            name='date',
        ),
    ]
