# Generated by Django 3.2 on 2021-06-29 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0019_remove_cryptostock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=9)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assets', models.ManyToManyField(blank=True, to='welcome.StockAsset')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='welcome.Portfolio'),
        ),
    ]
