# Generated by Django 3.2 on 2021-06-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0020_auto_20210629_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='assets',
        ),
        migrations.AddField(
            model_name='stockasset',
            name='portfolio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='welcome.portfolio'),
            preserve_default=False,
        ),
    ]
