# Generated by Django 3.2 on 2021-06-30 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0021_auto_20210629_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockasset',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.portfolio'),
        ),
    ]
