# Generated by Django 3.2 on 2021-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0022_alter_stockasset_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=9)),
                ('area', models.CharField(max_length=9)),
                ('industry', models.CharField(max_length=9)),
                ('list_date', models.CharField(max_length=9)),
            ],
        ),
    ]
