# Generated by Django 3.2 on 2021-06-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0024_auto_20210630_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='value',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sunkvalue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stockasset',
            name='buyPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
