# Generated by Django 3.2 on 2021-06-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0025_auto_20210630_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
