# Generated by Django 3.2 on 2021-06-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0026_auto_20210630_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='earnings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockasset',
            name='earnings',
            field=models.FloatField(default=0.0),
        ),
    ]
