# Generated by Django 3.2 on 2021-07-13 22:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0027_auto_20210630_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sunkvalue', models.FloatField(default=0.0)),
                ('value', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('earnings', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicStockAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=9)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField()),
                ('buyPrice', models.FloatField(default=0.0)),
                ('value', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('earnings', models.FloatField(default=0.0)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.portfolio')),
            ],
        ),
    ]
