# Generated by Django 3.2 on 2021-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0031_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='screens',
            field=models.ManyToManyField(blank=True, to='welcome.Screen'),
        ),
    ]
