# Generated by Django 3.2 on 2021-07-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcome', '0032_profile_screens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='screens',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='author',
        ),
        migrations.AddField(
            model_name='screen',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
