# Generated by Django 3.2 on 2021-07-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0033_auto_20210714_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=9)),
                ('volume', models.IntegerField(default=0.0)),
                ('value', models.FloatField(default=0.0)),
                ('screen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.screen')),
            ],
        ),
    ]
