# Generated by Django 3.2 on 2021-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0035_auto_20210721_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinastock',
            name='change',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinastock',
            name='close',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinastock',
            name='high',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinastock',
            name='low',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinastock',
            name='open',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinastock',
            name='volume',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
