# Generated by Django 3.2 on 2021-09-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0036_auto_20210825_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptostock',
            old_name='adjclose',
            new_name='market_cap',
        ),
        migrations.RenameField(
            model_name='cryptostock',
            old_name='volume',
            new_name='max_supply',
        ),
        migrations.RenameField(
            model_name='cryptostock',
            old_name='change',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cryptostock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='cryptostock',
            name='low',
        ),
        migrations.RemoveField(
            model_name='cryptostock',
            name='open',
        ),
        migrations.AddField(
            model_name='cryptostock',
            name='name',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
